### ISSUE TITLE
Is it possible to change the licence to Apache 2.0?

### ISSUE THREAD

**Issue by barvin** [reportportal/logger-java-logback#2]
It would be much easier for commercial products development, if this library had an Apache 2.0 license. I would like to use agent-java-testNG, overriding some methods, in my commercial project and also use classes from logger-java-logback in imports. I cannot do this, if it has GPL license, only use it as a dependency as is.
Thank you!

**Comment by filland** [comment]
@barvin sorry for the delay, the license changed to Apache 2.0.

**Comment by barvin** [comment]
@filland thank you!
