### ISSUE TITLE
Multiple Launch in RP with Grid Execution 

### ISSUE THREAD

**Issue by vaibhavshukl12** [reportportal/logger-java-logback#20]
Hi All.
Is there any solution in the report portal for parallel execution.
I integrated, RP with TestNG, and I implemented a grid also but I want multiple launches depends on nodes in grid how I can achieve this.
I want different launches with respective nodes.

**Comment by evjlobanova** [comment]
@Vaibhavshukla08 Could you please check our dev guide https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch
Does it resolve you issue?

**Comment by HardNorth** [comment]
Off-topic
