### ISSUE TITLE
Logging from junit extension doesn't work

### ISSUE THREAD

**Issue by petersramek** [reportportal/logger-java-logback#25]
Hello!

I have came across an issue when I'm trying to log messages into reportportal from junit 5 extension context callbacks.
https://junit.org/junit5/docs/current/user-guide/#extensions-lifecycle-callbacks-before-after-execution

**Steps to reproduce:**

Here is the class which should ensure logging to be executed before each test(**log does not apperar in reportportal**)
```java
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class MyCallback implements BeforeEachCallback {

    @Override
    public void beforeEach(ExtensionContext extensionContext) throws Exception {
        log.info("Logging from BeforeEach");
    }
}
```

**Test class itsef:**
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import com.epam.reportportal.junit5.ReportPortalExtension;
import com.ferratum.testing.MyCallback;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@ExtendWith({ReportPortalExtension.class,MyCallback.class})
public class RpTest {

    @Test
    void simpleTest() {
        log.info("Logging from test");
    }
}
```
**Log output in intelliJ**
12:47:12.501 INFO  MyCallback - main - Logging from BeforeEach
12:47:12.519 INFO  RpTest - main - Logging from test

Process finished with exit code 0

**ReportPortal output**
![image](https://user-images.githubusercontent.com/26471389/120182453-b829a600-c20e-11eb-922f-7ffe4dc060e2.png)

**Dependecies**
```xml
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.16</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-junit5</artifactId>
            <version>5.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>5.0.3</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.7.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
    </dependencies>
```

Can you please check whether this is issue or currently unsupported functionality?
Thanks in advance!

**Comment by gerrnot** [comment]
For me, the problem was that I searched for my logs in the wrong place.

I navigated Launch -> Class -> Logs, it showed no test logs.
When I instead navigated Class -> method, I saw the test logs.

Not sure If this is the same issue for you!

**Comment by HardNorth** [comment]
@petersramek This shouldn't work by design. `BeforeEachCallback` is a JUnit `Extension` and Report Portal agent is an `Extension` too. We report test data, not extension data. The only extension which might work for your case is `InvocationInterceptor` due to its synchronous nature.
