### ISSUE TITLE
xlsx attachment is defined as x-tika-ooxml

### ISSUE THREAD

**Issue by perelygina** [reportportal/logger-java-logback#26]
Hello!
I am trying to attach an xlsx file to the report as in the example https://github.com/reportportal/logger-java-logback

However, when downloading it, I get a file called attachment_8146539.x-tika-ooxml
Report Portal Build: 5.4.0

        File file = File.createTempFile("test-file", ".xlsx");
        log.info("RP_MESSAGE#FILE#{}#{}", file.getAbsolutePath(), "I'm logging content via temp file");

Please help me to solve this problem.
Thank you!

**Comment by HardNorth** [comment]
@perelygina Should be fixed in the latests agent versions
