### ISSUE TITLE
Typo with artifactId  in README.md file 

### ISSUE THREAD

**Issue by SergeVKom** [reportportal/logger-java-logback#37]
**Describe the bug**
Typo in the https://github.com/reportportal/logger-java-logback/blob/develop/README.md

**Steps to Reproduce**

**Expected behavior**
<dependency>
    <groupId>com.epam.reportportal</groupId>
    <artifactId>logger-java-logback</artifactId>
    <version>5.1.6</version>
    <scope>test</scope>
</dependency>

**Actual behavior**
<dependency>
    <groupId>com.epam.reportportal</groupId>
    <artifactId>logger-java-log4j</artifactId>
    <version>5.1.6</version>
    <scope>test</scope>
</dependency>

**Dependency versions**

**Additional context**

**Comment by HardNorth** [comment]
Fixed
